language: php

php:
  - 7.2
  - 7.3

matrix:
  allow_failures:


before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: ./vendor/bin/phpunit --configuration phpunit.travis.xml --coverage-text
